### ISSUE TITLE
`Setup Homebrew` action started failing

### ISSUE THREAD

**Issue by bruuuuuuuce** [Homebrew/actions#334] opened 2023-02-17 21:44 UTC
Inside of our public tap, the `setup-homebrew` action has started failing with `Error: The process '/usr/bin/bash' failed with exit code 128`. It was working this morning, but now when we even try running it with an empty commit, it keep failing with the same error message. We enabled debug logging to see if we could debug further. It looks like maybe the `/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core` directory doesn't exist?

<img width="839" alt="Screen Shot 2023-02-17 at 1 34 00 PM" src="https://user-images.githubusercontent.com/11823378/219799248-86edc110-09cd-4cf4-aedd-6bbf28df2bc0.png">

**Comment by bruuuuuuuce** [comment] 2023-02-17 21:45
@cprice404

**Comment by Bo98** [comment] 2023-02-17 21:56
Duplicate of #333 - I'm already working on a fix.

**Closed by Bo98** 2023-02-17 21:56 UTC
